# Generated by Django 5.2.8 on 2025-11-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.RemoveField(
            model_name='sell',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='service',
            name='unit',
        ),
        migrations.DeleteModel(
            name='TermsAndConditions',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Sell',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
