# Generated by Django 5.2.8 on 2025-11-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='PrivacyPolicy',
        ),
        migrations.DeleteModel(
            name='TermsAndConditions',
        ),
    ]
